version: '2.1'

services:
  sut:
    build: .
    environment:
      - PORT=12345

  tester:
    image: subfuzion/netcat
    depends_on:
      sut:
        condition: service_healthy
    entrypoint: "/bin/ash"
    command: "-c 'nc -u -w1 sut 12345 < /etc/alpine-release'"
